env:
    - VERSION=3
    - VERSION=4
    - VERSION=5
    - VERSION=6
    - VERSION=7
    - VERSION=8
    - VERSION=9

command:
    - yarn add prom-client@"$VERSION" --dev
    - yarn --force
    - yarn test
